### ISSUE TITLE
Example app and my own app don't work on lower SDK's

### ISSUE THREAD

**Issue by halileohalilei** [meNESS/EasyIntro#11]
I have two Genymotion devices installed on my PC. One has SDK 18 and the other 22. The example app and the app I'm developing using this library works pretty well on the device with SDK 22. However they both crash on the device with SDK 18. I also have a real device with SDK 18 and they also crash on that device too. The stack trace is as following: 
```

FATAL EXCEPTION: main
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.meness.easyintro.app/io.github.meness.easyintro.app.MyEasyIntro}: android.view.InflateException: Binary XML file line #24: Error inflating class io.github.meness.easyintro.views.LeftToggleIndicator
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                  at android.os.Looper.loop(Looper.java:137)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                                               Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class io.github.meness.easyintro.views.LeftToggleIndicator
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                                  at android.support.v7.widget.ViewStubCompat.inflate(ViewStubCompat.java:200)
                                                                                  at io.github.meness.easyintro.EasyIntroCarouselFragment.inflateIndicatorContainer(EasyIntroCarouselFragment.java:704)
                                                                                  at io.github.meness.easyintro.EasyIntroCarouselFragment.onViewCreated(EasyIntroCarouselFragment.java:655)
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1123)
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                                  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                                                  at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                                  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
                                                                                  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                                                  at android.app.Activity.performStart(Activity.java:5143)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                  at android.os.Looper.loop(Looper.java:137) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                  at android.support.v7.widget.ViewStubCompat.inflate(ViewStubCompat.java:200) 
                                                                                  at io.github.meness.easyintro.EasyIntroCarouselFragment.inflateIndicatorContainer(EasyIntroCarouselFragment.java:704) 
                                                                                  at io.github.meness.easyintro.EasyIntroCarouselFragment.onViewCreated(EasyIntroCarouselFragment.java:655) 
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1123) 
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                                  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
                                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
                                                                                  at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                                  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619) 
                                                                                  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171) 
                                                                                  at android.app.Activity.performStart(Activity.java:5143) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                  at android.os.Looper.loop(Looper.java:137) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                               Caused by: android.content.res.Resources$NotFoundException: File res/drawable/toggle_indicators_bg.xml from drawable resource ID #0x7f020051
                                                                                  at android.content.res.Resources.loadDrawable(Resources.java:2091)
                                                                                  at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                                                                  at android.view.View.<init>(View.java:3364)
                                                                                  at android.widget.ImageView.<init>(ImageView.java:121)
                                                                                  at android.widget.ImageButton.<init>(ImageButton.java:87)
                                                                                  at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:57)
                                                                                  at io.github.meness.easyintro.views.AbstractToggleIndicator.<init>(AbstractToggleIndicator.java:0)
                                                                                  at io.github.meness.easyintro.views.AbstractToggleIndicator.<init>(AbstractToggleIndicator.java:0)
                                                                                  at io.github.meness.easyintro.views.LeftToggleIndicator.<init>(LeftToggleIndicator.java:0)
                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                                  at android.support.v7.widget.ViewStubCompat.inflate(ViewStubCompat.java:200) 
                                                                                  at io.github.meness.easyintro.EasyIntroCarouselFragment.inflateIndicatorContainer(EasyIntroCarouselFragment.java:704) 
                                                                                  at io.github.meness.easyintro.EasyIntroCarouselFragment.onViewCreated(EasyIntroCarouselFragment.java:655) 
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1123) 
                                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
                                                                                  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
                                                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
                                                                                  at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                                  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619) 
                                                                                  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171) 
                                                                                  at android.app.Activity.performStart(Activity.java:5143) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                                  at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                  at android.os.Looper.loop(Looper.java:137) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                               Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                                  at android.content.res.TypedArray.getColor(TypedArray.java:326)
                                                                                  at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:967)
                                                                                  at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:901)
                                                                              	at android.graphics.drawable.StateListDrawable.inflate(Stat
```

**Comment by jaypoojara** [comment]
i am facing same problem.

**Comment by meNESS** [comment]
@halileohalilei @jaypoojara Thanks for reporting this issue. I found the problem and trying to solve it in the next release.

**Comment by sathishmscict** [comment]
Hi am also face same problem,  The example app and the app I'm developing using this library works pretty well on the device with SDK 22. However they  crash on the device with **below SDK 22.**

**Comment by sathishmscict** [comment]
Problem in colorcode as 
android:color="?attr/toggleIndicatorsPressed"
am removing above attribute its working fine for me.

**Comment by meNESS** [comment]
I already know about the issue and I'm really sorry for not fixing it till today. I'm working on v4.0 with huge changes (including fixed this issue).

**Comment by Zapnologica** [comment]
Good day, I am experiencing this issue as well.  I need to publish new version of app. Is there any quick work around until v4.0 is released?

**Comment by cutiko** [comment]
Greetings I'm having the same problem with a friend of mine so +2 to this issue.

We check the code here on Github and can't figure why is crashing, the LeftTogleIndicator inherits from an abstract class from the library, and that class inherits from CompatButton, so it should be fine.... we are very confused about this :C
