### ISSUE TITLE
App is crashing when I try to use some Indicator Methods

### ISSUE THREAD

**Issue by Crusher7** [meNESS/EasyIntro#13]
I tried to use `withPageIndicator(false);` in my project but it causeed my app to crash , I also tried that in the sample project but it crashed as well , What is the reason?

This is the error which i got 

```
FATAL` EXCEPTION: main
Process: io.github.meness.easyintro.app, PID: 19835
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.meness.easyintro.app/io.github.meness.easyintro.app.MyEasyIntro}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5258)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
                                                                                    at io.github.meness.easyintro.EasyIntroCarouselFragment.withPageIndicatorVisibility(EasyIntroCarouselFragment.java:314)
                                                                                    at io.github.meness.easyintro.EasyIntro.withPageIndicatorVisibility(EasyIntro.java:271)
                                                                                    at io.github.meness.easyintro.app.MyEasyIntro.initIntro(MyEasyIntro.java:36)
                                                                                    at io.github.meness.easyintro.EasyIntro.onCarouselViewCreated(EasyIntro.java:124)
                                                                                    at io.github.meness.easyintro.EasyIntroCarouselFragment.onViewCreated(EasyIntroCarouselFragment.java:653)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1127)
                                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
                                                                                    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                                    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
                                                                                    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:604)
                                                                                    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
                                                                                    at android.app.Activity.performStart(Activity.java:6006)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5258) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by meNESS** [comment]
@Crusher7 You're not using the latest version because there's no such `withPageIndicator(boolean)` method. Use the latest version please. I tried the latest version sample app and there's no problem with setting `withPageIndicatorVisibility(boolean)`. If I'm wrong, please provide more info, thanks.

**Comment by Crusher7** [comment]
No, I think I'm using the latest one
here is what I used in the dependencies:
`compile 'io.github.meness:easyintro:2.9.16'`

**Comment by meNESS** [comment]
@Crusher7 Fixed, thanks for reporting 👍
